### ISSUE TITLE
Omni completion or YCM

### ISSUE THREAD

**Issue by kursion** [othree/tern-coffee#1]
Hi,

I'm a big fan of YCM plugin. Tern for vim is working with it pretty well. For instance, 
you can have an object

``` javascript
a = {t1: "test1", t2: "test2"}
```

And if you write `a.` you will see some suggestion based on the object `a`. Actually, this is not working for coffeescript :( Any ideas how to resolve this issue or any other plugins ? Best regards.

**Comment by othree** [comment]
Try install https://github.com/othree/tern_for_vim_coffee

**Comment by kursion** [comment]
Already done this, sorry not mentionned it. The autocompletion doesn't work :(

Can you tell me if it should work ?

**Comment by othree** [comment]
This is hard to debug. I think YCM will call omnicomplete function when available.
So can you check it when `&filetype` is `coffee`

```
echom &omnifunc
```

It should be `tern#Complete`
If you have it set correct.
Then you should make sure your tern-coffee installed in correct location.
If everything looks correct/
Maybe you can use `Ctrl+X`, `Ctrl+O` to trigger omni complete by yourself.

**Comment by kursion** [comment]
Hi and thanks for your time.
`echom &filetype` is `coffee`
`echom &omnifunc` is `tern#Complete`

Now for the location I'm not sure if it's correct. I have 

``` vim
149 Plugin 'marijnh/tern_for_vim'
150 Plugin 'othree/tern_for_vim_coffee'
```

Thus I have both folders : `bundle/tern_for_vim` and `bundle/tern_for_vim_coffee`
I went into `bundle/tern_for_vim` and did `npm install && npm install tern-coffee`

Is the last part correct ? I'm having some troubles to understand the doc clearly. Should I do 
`npm install tern-coffee` in `bundle/tern_for_vim_coffee` ?

PS: Ctrl+X, Ctrl+O doesn't nothing

**Comment by othree** [comment]
You have correctly installed the plug-in.
One last thing is you will need `.tern-project` file to choose which tern plug-in to use.
