### ISSUE TITLE
Request fails due to error

### ISSUE THREAD

**Issue by katspaugh** [othree/tern-coffee#2]
When I do a type request in a CoffeeScript file, tern throws an error and quits:

```
/usr/local/lib/node_modules/tern/plugin/coffee.js:261
        line = compiled.reverseMap[cursor.line - lastj];
                                  ^
TypeError: Cannot read property 'NaN' of undefined
    at preRequest (/usr/local/lib/node_modules/tern/plugin/coffee.js:261:35)
    at Object.server.request (/usr/local/lib/node_modules/tern/plugin/coffee.js:371:17)
    at respond (/usr/local/lib/node_modules/tern/bin/tern:205:10)
    at IncomingMessage.<anonymous> (/usr/local/lib/node_modules/tern/bin/tern:171:32)
    at IncomingMessage.emit (events.js:92:17)
    at _stream_readable.js:944:16
    at process._tickCallback (node.js:442:13)
```

Tern is version 0.6.2, coffee-script 1.6.1 (as specified in the tern-coffee dependencies).

The same type request works fine in a JavaScript file.

**Comment by othree** [comment]
Any sample code?
Or every CoffeeScript file?
How about issue #4, looks like not every CoffeeScript file have this issue.

**Comment by katspaugh** [comment]
Yes, with the simple file in #4 it doesn't throw an error. This file does reproduce the error: https://github.com/katspaugh/ng-shariki/blob/master/src/app.coffee

**Comment by othree** [comment]
I think this is the same issue as #4 .
Please try again with .tern-project file.

**Comment by katspaugh** [comment]
Here's my `.tern-project` in the directory containing the file linked to above:

```
{
  "libs": [
    "browser",
    "ecma5"
  ],
  "plugins": {
    "angular": {},
    "coffee": {}
  },
  "loadEagerly": [
    "src/*.js"
  ]
}
```

Please, also note that the stack trace in the error message suggests the error comes from the plugin code:

```
/usr/local/lib/node_modules/tern/plugin/coffee.js:261
```

It means the Tern plugin was registered.

**Comment by othree** [comment]
Could you try update tern to latest version?
I am using 0.8.0 and it works.

**Comment by katspaugh** [comment]
I get the same error with tern 0.8.0. OK, never mind. I'll try to debug and solve this myself. Will let you know.
