### ISSUE TITLE
Node modules directory incorrect in coffee.js

### ISSUE THREAD

**Issue by katspaugh** [othree/tern-coffee#3]
The plugin assumes the location of the coffee-script module [here](https://github.com/othree/tern-coffee/blob/master/coffee.js#L8):

```
      require('./node_modules/coffee-script/lib/coffee-script/lexer'),
      require('./node_modules/coffee-script/lib/coffee-script/parser')
```

This is not where the `node_modules` directory can be found on my system. I think, it's better to require a path, relative to the npm module, like this:

```
      require('coffee-script/lib/coffee-script/lexer'),
      require('coffee-script/lib/coffee-script/parser')
```

**Comment by othree** [comment]
Follow the installation guide in README.

```
cd ~/.vim/bundle/tern_for_vim
npm install tern-coffee
```

Use npm install tern-coffee  at the location of tern_for_vim.

**Comment by katspaugh** [comment]
Why not make it more universal with the suggested change? The thing is, I install my Emacs plugin from a repository and it would be a hassle to reinstall tern-coffee in the plugin directory generated by Emacs.

**Comment by othree** [comment]
Because I need fix the version of coffee-script to prevent the coffee-script inner api change affects tern-coffee.
Also, use node module to provide third-party tern plugin is valid.

**Comment by katspaugh** [comment]
But the suggested change does work with coffee-script installed via `npm install` in the tern-coffee directory.

**Comment by othree** [comment]
Now I know what your code means.
But it is not working while I wrote the code.
Maybe node API was changed.
I will need to test it.

And I'm interesting in the location of your node_modules.

**Comment by katspaugh** [comment]
It's quite possible the API has changed.

My node modules are in `/usr/local/lib` (it's OS X and brew).

**Comment by othree** [comment]
It looks like global modules.
If you execute 'npm install' in a folder with package.json.
It should create **node_modules** folder to store local node modules.
I am wondering where is your local modules.
If you follow the installation guide.

BTW, you should execute `npm install tern-coffee` in **tern_for_vim** folder(If you use Vim with tern).
Not execute `npm install` under **tern-coffee** folder.
