### ISSUE TITLE
Can't infer a type in simple code

### ISSUE THREAD

**Issue by katspaugh** [othree/tern-coffee#4]
Here's my test code:

```
obj =
    hello: 'world'
    num: 10

obj.hello
```

Which compiles into this JavaScript:

```
// Generated by CoffeeScript 1.6.1
(function() {
  var obj;

  obj = {
    hello: 'world',
    num: 10
  };

  obj.hello;

}).call(this);
```

Trying to request the type of `obj.hello` in CoffeeScript returns unknown type.

**Comment by othree** [comment]
Just test.
I think you miss the [.tern-project](http://ternjs.net/doc/manual.html#configuration) file part in installation guide.
Plugins always require this file to active.
